config/routes.rb
Supramap::Application.routes.draw do

  resources :projects
  resources :sfiles
  match 'job/:id/color_kml' => 'job#color_kml', as: :color_kml

  root to: 'supramap#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/job.rb
require 'cgi'
require 'color_kml'
require 'poy_service'

class Job < ActiveRecord::Base
  include ColorKML
  include SupramapExceptions
  belongs_to :project
  has_and_belongs_to_many :sfiles

  validates :name, presence: true
  validates :name, uniqueness: {:scope => :project_id}
  validates :color_alignment, presence: true, :if => "color_type == 2"
  validates :color_alignment, numericality:{ :only_integer => true } , :allow_nil => true
  validates_with JobValidator

  after_create :create_job_dir
  after_destroy :delete_job_dir

  # create job dir before job is started
  def create_job_dir
    begin
      path = "#{FILE_SERVER_ROOT}/#{self.project.user.login}/#{self.project_id}/#{self.id}/"
      logger.error("Creating job dir: #{path}")
      FileUtils.mkdir(path)
      FileUtils.chmod_R(0777, path)
    rescue
      logger.error("An error occurred creating job dir for job: #{self.id}")
      return false
    end
  end

  # delete job dir after destroyed
  def delete_job_dir
    PoyService.delete(self.job_code) unless self.job_code.nil?

    path = "#{FILE_SERVER_ROOT}/#{self.project.user.login}/#{self.project_id}/#{self.id}/"
    FileUtils.rm_r(path) if File.exist?(path)

    if self.status == "Running"
      self.stop
    end
  end

  def start
    self.status = "Abnormal Exit"
    self.save
    project_path = "#{FILE_SERVER_ROOT}/#{self.project.user.login}/#{self.project_id}/"
    job_path = project_path+"#{self.id}/"


    read_poy_script_segment =''
    sfiles.each { |f|
      case f.filetype
        when "geo"
          read_poy_script_segment<<""
        when "AA"
          read_poy_script_segment<<"read(aminoacids: (\"#{f.name}\"))\n"
        when "pre"
          read_poy_script_segment<<"read(prealigned: (\"#{f.name}\", tcm:(1,1)))\n"
        when "fasta"
          read_poy_script_segment<<"read(\"#{f.name}\")\n"
        when "cat"
          read_poy_script_segment<<"read(\"#{f.name}\")\n"
        when "tree"
          read_poy_script_segment<<"read(\"#{f.name}\")\n"
      end
    }

    file_types = sfiles.collect {|f| f.filetype}
    poy_search = ""
    unless Sfile.equal_file_types?(file_types, "tree", "cat", "geo")
      poy_search = "transform(tcm:(1,1))\nsearch(max_time:0:0:5, memory:gb:2)\nselect(best:1)"
    end
    poy_script="#{read_poy_script_segment}
set(log: \"poy.log\")
#{poy_search}"

    poy_script << "\ntransform (static_approx)\n" unless Sfile.subset_file_types?(file_types, "pre")
    poy_script << "report (\"report.nexus\", nexus, trees:(nexus))
report(\"#{name}_results.kml\", kml:(supramap, \"#{sfiles.select { |file| file.filetype == "geo" }[0].name}\"))
report(asciitrees)
report(\"#{name}_results.tre\",trees)
report(\"#{name}_results.stats\",treestats)
exit()"

    File.open(job_path + "script.psh", 'w') { |f|
      f.write(poy_script)
    }

    poy_job_id = PoyService.init()
    raise POYWSInitError if poy_job_id == -1

    self.job_code =  poy_job_id

    PoyService.add_text_file(poy_job_id, "script.poy", poy_script)
    sfiles.each { |f|
      PoyService.add_text_file(poy_job_id, f.name, File.open("#{project_path}#{f.name}", "r").read)
    }

    res = PoyService.submit_poy(poy_job_id, 60)

    self.status = "Running"
    self.save
  end

  def is_done?
    if PoyService.is_done?(self.job_code)
      begin
        path = "#{FILE_SERVER_ROOT}/#{self.project.user.login}/#{self.project_id}/#{self.id}/"
        # array of files to retrieve from the poy-ws
        files = %W[output.txt #{name}_results.kml #{name}_results.tre #{name}_results.stats report.nexus]
        files.each do |f|
          write_file_from_poy_service(self.job_code, f, path)
        end
        self.status = "Completed"
        self.save
      rescue Exception => e
        self.status = "Failed"
        self.save
        logger.error("An error occurred checking/downloading the results of a poyws job.")
        logger.error(e.message)
        logger.error(e.backtrace)
      end
    end
  end

  def create_colored_kml
    path = "#{FILE_SERVER_ROOT}/#{project.user.login}/#{project_id}/#{id}/"
    kml_file_str = File.open( path + "#{name}_results.kml", "r" ).read
    colored_kml_str = ""
    if color_type == 1
      colored_kml_str = color_kml(kml_file_str)
    elsif color_type == 2
      colored_kml_str = color_kml(kml_file_str, color_alignment)
    end

    File.open( path + "#{name}_colored_results.kml", "w") do |f|
      f.write(colored_kml_str)
    end
  end

  protected
  def write_file_from_poy_service(job_code, file_name, dir_path)
    file_string = PoyService.get_file(job_code, file_name)
    File.open(dir_path + file_name, 'w') { |f| f.write(file_string) }
  end
end

app/controllers/job_controller.rb
class JobController < ApplicationController

  def define
    @project = Project.find(params[:id])
    @sfiles = Sfile.find_all_by_project_id(@project.id)
  end
  
  def select_files
    if params['cancel']
      redirect_to(:controller => "project", :action => "show", :id => params[:job][:project_id])
    else
      @sfiles = Sfile.find_all_by_project_id(params[:job][:project_id])
    end
  end

  def delete
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = "Job #{@job.name} successfully deleted."
    redirect_to(:controller => "project", :action => "show", :id => @job.project_id)
  end

  
  def create
    if params['cancel']
      redirect_to(:controller => "project", :action => "show", :id => params[:job][:project_id])
      return
    end

    @job = Job.new(params[:job])

    if @job.save
      begin
        @job.start
        flash[:notice] = "Job #{@job.name} successfully created and started."
        redirect_to(:controller => "project", :action => "show", :id => @job.project_id)
        return
      rescue
        @job.destroy
        # don't need to show flash message if errors exist
        flash[:notice] = "Job #{@job.name} could not be started." if @job.errors.empty?
      end
    end

    @project = Project.find(@job.project_id)
    @sfiles = Sfile.find_all_by_project_id(@project.id)
    render(:action => "define")
  end

  def show_color
    @job = Job.find_by_id(params[:id])
  end

  def color_kml
    puts params
    @job = Job.find_by_id(params[:id])

    if params['cancel']
      redirect_to(:controller => "project", :action => "show", :id => @job.project_id)
      return
    end

    if @job.update_attributes(params[:job])
      @job.create_colored_kml
      redirect_to(:controller => "project", :action => "show", :id => @job.project_id)
      return
    else
      render :show_color
    end
  end
end

app/helpers/job_helper.rb
require 'set'

module JobHelper

  # exts is a set because a category of files could have
  # a number of file extensions, e.g, fasta, fa, fn, fas
  def get_files_by_type(files, type)
    files.find_all {|file| file.filetype == type}
  end
  
  def show_files(sfiles)
    render(:partial => "sfile", :collection => sfiles)
  end
  
  # locals should contain:
  #   title = title of table
  #   files = array of sfiles
  #   file_exts = the type of files the table should display, i.e., csv
  def show_table_for_files(locals={})
    files = get_files_by_type(locals[:files], locals[:file_type])
    unless files.empty?
      locals[:files] = files
      render(:partial => "sfile_table", :locals => locals)
    end
  end
end

app/views/job/_sfile.html.erb
<tr>
    <td>
        <%= check_box_tag "job[sfile_ids][]", sfile.id %>&nbsp;<i><%=h sfile.name%></i>
    </td>
</tr>

app/views/job/_sfile_table.html.erb
<table class="files">
    <tr>
        <th align="left">
            <%= title %>
        </th>
    </tr>
    <%=show_files(files)%>
</table>

app/views/job/define.html.erb
<% title("Create Job") %>
<%= error_messages_for 'job' %>
<fieldset>
  <legend>job info</legend>
  <%= form_for :job, :url => {:action => "create"} do |form| %>
      <input type="hidden" name="job[project_id]" value="<%= h(@project.id) %>"/>
      <table class="job">
        <tr>
          <td colspan="2">name:&nbsp;<%= form.text_field :name, :size => 40 %></td>
        </tr>

      </table>
      </fieldset>
<fieldset>
    <legend>
        job files</i>&nbsp;
        <font size="1">
            (<a href="#">Which files should I choose?</a>)
        </font>
    </legend>
    <%=show_table_for_files({:files => @sfiles, :file_type => "geo", :title => "Geographical files:"})%>
    <%=show_table_for_files({:files => @sfiles, :file_type => "fasta", :title => "Sequence files:"})%>
    <%=show_table_for_files({:files => @sfiles, :file_type => "pre", :title => "Pre-aligned sequence files:"})%>
    <%=show_table_for_files({:files => @sfiles, :file_type => "cat", :title => "Categorical character files:"})%>    
    <%=show_table_for_files({:files => @sfiles, :file_type => "tree", :title => "Tree files:"})%>
  <%= submit_tag "Run Job", :class => "submit" %>
  <%= submit_tag "Cancel", :name => "cancel", :class => "submit" %>
    <% end %>
</fieldset>

app/views/job/show_color.html.erb
<% title("Color KML") %>
<script type="text/javascript">
    function toggleAlignment(colorType) {
        el = document.getElementById("job_color_alignment");
        if( colorType == 1) {
            el.value = "";
            el.disabled = true;
        } else {
            el.disabled = false;
            el.focus();
        }
    }
</script>

<style>
  .color-kml {
      text-align: left;
      padding-left: 30px;
      margin-bottom: 20px;
  }
</style>
<div><%= error_messages_for 'job' %></div>
<fieldset>
  <legend>color kml&nbsp;&nbsp; <font size="2">(<%= link_to "tutorial", "/supramap/tutorials#kml-coloring" %>)</font></legend>
  <%= form_for @job, :url => color_kml_url(@job) do |f| %>
      <div class="color-kml">
        job:&nbsp;&nbsp;<%= @job.name %><br/><br/>
        <%= f.radio_button :color_type, "1", :onclick => "toggleAlignment(1);" %>
        &nbsp;Color branches based on a categorical data file<br/>
        <%= f.radio_button :color_type, "2", :onclick => "toggleAlignment(2);" %>
        &nbsp;Color branches based on an aligned column (starting at 1)
        <%= f.text_field :color_alignment, :size => 5 %>
        <br/>
      </div>
      <%= submit_tag "Color KML", :class => "submit" %>
      <%= submit_tag "Cancel", :name => "cancel", :class => "submit" %>
<% end %>
</fieldset>